---

- name: Setup
  hosts: all
  vars_files:
    - ./vars.yml
  roles:
    - role: gumgum-flask
  tags:
    - setup

- name: Deploy
  hosts: all
  vars_files:
    - ./vars.yml
  roles:
    - role: gumgum-flask
  tags:
    - deploy
